fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: trailing-whitespace
        exclude: '^docs/'
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        entry: autoflake -r -i --remove-all-unused-imports --remove-unused-variables
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff # linter
        types_or: [ python, pyi, jupyter, toml ]
        args: [ --fix ]
      - id: ruff-format # formatter
        types_or: [ python, pyi, jupyter, toml ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
